docs/CONTRIBUTING.md
[PR guideline.](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)
*If something is not applicable to your case - acknowledge the fact by writing n/a.*
<table>
<tr>
<td>Relevant issue tracker links</td>
<td>n/a</td>
</tr>
<tr>
<td>Linked PRs in other repos</td>
<td>n/a</td>
</tr>
<tr>
<td>Manual testing instructions</td>
<td>n/a</td>
</tr>
<tr>
<td>Breaking changes</td>
<td>n/a</td>
</tr>
<tr>
<td>Additional notes</td>
<td>n/a</td>
</tr>
</table>
* Localisation.
* Architectural decisions.
* Performance.
* Comments.
* Big feature tech design documentation.
* Readability.
* DRY.
* Are there any bicycles invented that should be replaced with existing code or external libs?
* Are there unit and e2e tests added?
=> Added link for cucumber e2e testing

src/models/chats/chat-invite-store.js
[PR guideline.](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)
*If something is not applicable to your case - acknowledge the fact by writing n/a.*
|    📝   |
| ------- |
| **Relevant issue tracker links:** | 
| https://peerio.tpondemand.com/entity/7304
https://peerio.tpondemand.com/entity/7239 |
| **Linked PRs in other repos:** | 
| https://github.com/PeerioTechnologies/peerio-desktop/pull/117 | 
| **Manual testing instructions:** | 
| tested and approved |
| **Breaking changes:** | 
| n/a |
| **Additional notes:** | 
| n/a |
* Localisation.
* Architectural decisions.
* Performance.
* Comments.
* Big feature tech design documentation.
* Readability.
* DRY.
* Are there any bicycles invented that should be replaced with existing code or external libs?
* …
=> fix: minor fix for new Room invites flow

src/copy/en.json
https://github.com/PeerioTechnologies/peerio-desktop/pull/177
^ see desktop PR
----
=> chore: update copy for new file upload dialog

src/copy/en.json
https://app.clubhouse.io/peerio/story/2643/mobile-files-copy-does-not-match
----
=> chore(copy): add title_empty

src/copy/en.json
for https://github.com/PeerioTechnologies/peerio-desktop/pull/240
discussed offline with Paul
----
=> chore: final copy for room invite when over room limit

src/copy/en.json
https://app.clubhouse.io/peerio/story/819/desktop-cancel-signup
https://github.com/PeerioTechnologies/peerio-desktop/pull/251
----
=> chore: cancel text in signup flow

src/copy/en.json
https://app.clubhouse.io/peerio/story/302/mobile-unable-to-cancel-downloads
mobile PR coming later today
info on mobile PR when it's ready
----
=> chore: text for new file preview screen

src/copy/en.json
=> chore: we is serious

src/copy/en.json
=> chore(copy): update peerio ID learn more line

src/models/contacts/contact.js
For supporting filtering. https://app.clubhouse.io/peerio/story/7500/sdk-support-applabel-in-contact-lookup
Nothing yet. Desktop stories to come. 
----
=> feat: support appLabel in profile

src/copy/en.json, src/models/chats/chat-head.js, src/models/chats/chat-store.js, src/models/chats/chat-store.spaces.js, src/models/chats/chat.js, test/e2e/code/world.js
https://app.clubhouse.io/peerio/story/7833/medcryptor-desktop-wiring-of-rooms-sdk-to-markup
----
=> feat: wiring of rooms sdk to markup

src/helpers/file.js, src/models/files/file.js, test/unit/helpers/file.test.js
See https://github.com/PeerioTechnologies/peerio-icebear/pull/200
----
=> fix: migitate Unicode text direction confusion with file extensions

src/copy/en.json
=> chore: limited actions dialog copy update

src/copy/en.json
=> chore(copy): "Continue using older version" -> "Update later"

src/copy/en.json
https://app.clubhouse.io/peerio/story/8900/creating-rooms-inside-patient-space-say-new-dm
https://github.com/PeerioTechnologies/peerio-desktop/pull/327
see desktop PR
----
=> chore: copy for new internal/patient room placeholders

package.json, src/models/contacts/contact-store.js, src/models/volumes/volume-store.js
shareFolder is now more complex and everything else is less complex.
=> Mobile fixes

src/copy/en.json
https://github.com/PeerioTechnologies/peerio-desktop/pull/342
just copy here, see desktop PR for changes
----
=> chore: copy for 'pending' file tooltip

src/models/contacts/contact.js, test/e2e/code/app.js, test/e2e/code/helpers/contacts.js, test/e2e/code/steps/contacts.js, test/e2e/code/steps/medcryptor.js, test/e2e/code/world.js, test/e2e/spec/contacts/contacts.feature, test/e2e/spec/contacts/medcryptor_contacts.feature
https://app.clubhouse.io/peerio/story/7834/desktop-remove-clerk-s-ability-to-promote-doctor-to-admin
----
=> feat: add medcryptor roles to contact profile

src/copy/en.json
https://app.clubhouse.io/peerio/story/7257/newfs-tell-user-that-folder-will-be-moved-to-root-when-sharing-it
https://github.com/PeerioTechnologies/peerio-desktop/pull/346
n/a, see desktop
----
=> chore: copy for 'move to root' notif for sharing nested folder

src/copy/en.json
=> chore: copy for 2FA input placeholder

.eslintrc.js, benchmarks/crypto.js, benchmarks/index.js, benchmarks/measure.js, package.json
Currently benchmarking some crypto only.
Also disables no-await-in-loop rule for ESLint, because it's a bad rule.
----
=> chore: add benchmarks

src/copy/en.json
https://app.clubhouse.io/peerio/story/9689/desktop-message-errors
n/a just copy
----
=> chore: copy for message send error

src/copy/en.json
https://www.figma.com/file/QYnESxGrzLbqWVy6eSGS3I0I/8507-Drag-and-drop-flows
https://github.com/PeerioTechnologies/peerio-desktop/pull/364
----
=> chore: copy for drag and drop snackbars

src/copy/en.json
https://github.com/peeriotechnologies/peerio-icebear/tree/copy-file-unavailable
n/a
----
=> chore: copy for unavailable (deleted or removed) file

src/copy/en.json
https://app.clubhouse.io/peerio/story/10888/desktop-no-results-found
desktop: https://github.com/PeerioTechnologies/peerio-desktop/pull/388
n/a, see desktop PR
----
=> chore: updated copy for error_contactNotFound

test/e2e/code/steps/files.js
Since it's not being downloaded, just renamed.
----
=> chore(test): no need to cleanup renamed file

src/models/files/file-store-base.js, src/models/files/file-store.js
This was what made file renaming test occasionally fail.
Our e2e tests catch this pretty well :)
----
=> fix: file descriptor caching

src/models/chats/chat.js, src/models/contacts/tofu-store.js, src/models/kegs/shared-keg-db.js
1. Clear cache.
2. Reload.
3. Check that there are no tofu errors.
----
=> fix: tofu caching and other missing awaits

src/copy/en.json
https://app.clubhouse.io/peerio/story/12574/mobile-illustration-empty-folder-zero-state
https://github.com/PeerioTechnologies/peerio-mobile/pull/298
----
=> chore: copy update

src/models/server-settings.js
https://app.clubhouse.io/peerio/story/12151/server-support-setting-for-mixpanel-sign-up-trackers#activity=12844
same as: https://github.com/PeerioTechnologies/peerio-server/pull/723
----
=> feat: [ch12151] support for mixpanel token in settings

src/models/user/beacons.js, src/models/user/user.js, src/models/user/user.profile.js, test/e2e/code/steps/profile.js, test/e2e/spec/account/profile.feature
https://app.clubhouse.io/peerio/story/12721/sdk-beacon-state-management
----
=> feat: beacon state management

src/models/files/file.upload.ts
Upload a file in the Files view. It should work and show the file progress.
----
=> fix: set file uploadedAt and name before upload begins

src/helpers/retry.ts, src/models/user/user.auth.ts, src/network/socket-client.ts
1. In console, call `ice.socket.reset()`.
2. Quickly turn off internet connection. Within one second from 1 step.
3. Turn the connect back on after a few seconds.
4. Call `ice.socket.reset()` again and check that it disconnects and connects back. If it doesn't (no "💔 Socket disconnected." / "💚 Socket connected.", it's a bug.
----
=> fix: socket resetting and retries

src/models/chats/chat-invite-store.ts
*Unrelated to the test timeout on CI, but something I found when looking into the code*.
Make async action work.
Also, use observable array.replace instead of re-assigning its value in
case some code keeps a reference to it.
----
=> fix(chat-invite-store): async action

src/telemetry/strings.ts
https://app.clubhouse.io/peerio/story/14677/desktop-mixpanel-sign-in-sign-up-bugs-oct-11
desktop: https://github.com/PeerioTechnologies/peerio-desktop/pull/457
this has been tested and approved by Kaoru
----
=> chore: telemetry bugs/updates

src/network/socket-client.ts
=> fix(socket-client): reconnection fixes

src/telemetry/strings.ts
https://github.com/PeerioTechnologies/peerio-desktop/pull/463
https://app.clubhouse.io/peerio/story/15623/desktop-validatedinput-telemetry-bugs
n/a, copy only
----
=> chore: welcome_back telemetry string

src/defs/interfaces.ts, src/models/client-app.ts, src/models/user/user.2fa.ts
=> fix: 2fa req returns promise

src/models/kegs/shared-db-boot-keg.ts
https://app.clubhouse.io/peerio/story/15413/desktop-deleted-accounts-broken
----
=> chore: do not exclude deleted contacts from keg

src/copy/en.json
https://app.clubhouse.io/peerio/story/10029/quit-menu-item
https://app.clubhouse.io/peerio/story/2582/don-t-close-app-on-window-close
https://github.com/PeerioTechnologies/peerio-desktop/pull/462
----
=> chore(copy): title_quit and title_updateAndQuit

src/copy/en.json, src/models/chats/chat-store.ts, src/models/chats/my-chats.ts, src/models/files/file-folder.ts, src/models/files/file-store-base.ts, src/models/files/file.ts, src/models/kegs/keg.ts, src/models/user/user.ts, src/models/volumes/volume-store.ts, src/models/volumes/volume.ts
desktop: https://github.com/PeerioTechnologies/peerio-desktop/pull/474
=> Volume fixes

src/copy/en.json
https://github.com/PeerioTechnologies/peerio-mobile/pull/355
----
=> fix: copy change

.vscode/tasks.json, package.json, src/config.ts, src/crypto/keys.ts, src/crypto/secret.ts, src/crypto/util/conversion.ts, src/crypto/util/hashing.ts, src/crypto/util/random.ts, src/defs/buffer.d.ts, src/errors.ts, src/helpers/global-context.ts
=> chore: small type fixes from quick audit

src/copy/en.json
=> chore: correct period for 2fa token expiration

src/models/storage/memory-storage.ts, test/unit/helpers/mru-list.test.ts
=> test: use memory storage for mru test

src/helpers/validation/user-validators.ts
Small types fixup in the context of continuing TS work on desktop
No behaviour changes, only typings adjustments
----
=> chore: better inference in user-validators.ts

src/models/contacts/contact-store.ts, src/models/contacts/contact-store.whitelabel.ts
just typings changes, no behaviour modified
none needed if tests pass
----
=> chore: fix untyped contact store methods

src/helpers/unfurl/unfurl.ts
=> fix: don't try to fetch from IP or local domains; don't unfurl non-200 status

src/helpers/unfurl/types.ts, src/helpers/unfurl/unfurl.ts
Note that cached URLs won't have it.
---
-   [ ] Was tested and can be merged.
-   [ ] PR name follows conventional changelog format.
=> feat: add contentType to ExternalImage

src/models/user/user.ts
Removing check for passcode
https://app.clubhouse.io/peerio/story/17758/mobile-user-is-asked-to-sign-in-without-signing-out
There should be no "No passcode found" messages on login anymore.
=> fix: remove check for passcode [ch17758]

src/models/contacts/contact-store.ts, src/models/index.ts
needed just for types in:
https://app.clubhouse.io/peerio/story/18245/desktop-attempt-message-to-placeholder-message-leads-to-blue-screen-for-invited-user
n/a, see desktop PR for the real bug
---
-   [ ] Was tested and can be merged.
-   [ ] PR name follows conventional changelog format.
=> chore: export PendingDM model

src/copy/defs.ts, src/copy/en.json, src/copy/pseudo.json
https://github.com/PeerioTechnologies/peerio-desktop/pull/531
desktop PR has all the clubhouse links 
copy for desktop PR
---
-   [ ] Was tested and can be merged.
-   [ ] PR name follows conventional changelog format.
=> chore: title_peerioClosure
